[package]
name = "masser_gramain_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factor = "0.4.0"
fixed = "1.24.0"
fixed-sqrt = "0.2.5"
num-bigfloat = "1.7.0"

